### ISSUE TITLE
Invalid syntax diagnostic range

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#571]
Langium version: 0.5.0-next.f2b3802
Package name: langium

## Steps To Reproduce

1. Generate the hello-world project
2. Write incomplete text like this:

```
person Aasdf
person Jo

Hello Jo!
Hello 

```

## The current behavior

```
{
  severity: 1,
  range: {
    start: {
      character: NaN,
      line: NaN,
    },
    end: {
      character: NaN,
      line: NaN,
    },
  },
  message: "Expecting token of type 'ID' but found ``.",
  code: "parsing-error",
  source: "hello-world",
}
```

This results in this error message:

```
rejected promise not handled within 1 second: Error: Invalid arguments
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js-pretty.js:45765
stack trace: Error: Invalid arguments
	at new a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:87496)
	at new a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:84692)
	at asRange (hello-world/node_modules/vscode-languageclient/lib/common/protocolConverter.js:140:24)
	at asDiagnostic (hello-world/node_modules/vscode-languageclient/lib/common/protocolConverter.js:70:66)
	at convertBatch (hello-world/node_modules/vscode-languageclient/lib/common/utils/async.js:181:25)
	at Object.map (hello-world/node_modules/vscode-languageclient/lib/common/utils/async.js:190:17)
	at Object.asDiagnostics (hello-world/node_modules/vscode-languageclient/lib/common/protocolConverter.js:60:22)
	at LanguageClient.workDiagnosticQueue (hello-world/node_modules/vscode-languageclient/lib/common/client.js:990:19)
	at Immediate.<anonymous> (hello-world/node_modules/vscode-languageclient/lib/common/client.js:975:85)
	at processImmediate (node:internal/timers:464:21)
	at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

## The expected behavior

Proper ranges should be computed in any case.

**Comment by dhuebner** [comment]
@msujew 
I'm facing a `NaN` Range issue because the previous token has also `NaN` ranges. 
Does it make sense? 
The strange thing is that the previous token is also the first document token, so there is no range one can use. Would be maybe good in such a case just set the range to first document character.

**Comment by msujew** [comment]
@dhuebner I see, yeah, then we should simply set the error range to `0:0` (i.e. first line, first character).
