### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'GATE')

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#860]
Langium version: 1.0.1
Package name: chevrotain-allstar

## Steps To Reproduce

1. Clone https://github.com/JohannesMeierSE/position-dsl-langium
2. `npm i && npm run build`
3. Launch the extension and open  example1.posdia (in _examples_)
4. Mouse cursor at `n1.south_east` in line 2
5. ctrl+space for completion

## The current behavior

```
TypeError: Cannot read properties of undefined (reading 'GATE')
  at ChevrotainWrapper.<anonymous> (/workspace/position-dsl-langium/node_modules/chevrotain-allstar/lib/all-star-lookahead.js:108:57)
    at ChevrotainWrapper.orInternal (/workspace/position-dsl-langium/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:421:35)
    at ChevrotainWrapper.or (/workspace/position-dsl-langium/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:38:21)
    at ChevrotainWrapper.wrapOr (/workspace/position-dsl-langium/node_modules/langium/lib/parser/langium-parser.js:413:14)
    at LangiumCompletionParser.alternatives (/workspace/position-dsl-langium/node_modules/langium/lib/parser/langium-parser.js:30:22)
    at /workspace/position-dsl-langium/node_modules/langium/lib/parser/parser-builder-base.js:145:37
    at /workspace/position-dsl-langium/node_modules/langium/lib/parser/parser-builder-base.js:220:48
    at Array.forEach (<anonymous>)
    at /workspace/position-dsl-langium/node_modules/langium/lib/parser/parser-builder-base.js:220:30
    at LangiumCompletionParser.<anonymous> (/workspace/position-dsl-langium/node_modules/langium/lib/parser/langium-parser.js:329:17)
```

The error occurs at the line `const gate = orAlts[prediction].GATE;`

## The expected behavior

Completion should show a list of defined nodes.

**Comment by msujew** [comment]
Resolved in [`chevrotain-allstar@0.1.4`](https://github.com/langium/chevrotain-allstar/commit/8e223ad4d0e792a9f29dd2920e00a1d9ba944e4e).
